language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t tarunkrajsharma/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true tarunkrajsharma/docker-react npm run test





